<../../../mkconfig


TARG=kl

OFILES=\
	asm.$O\
	list.$O\
	noop.$O\
	sched.$O\
	obj.$O\
	optab.$O\
	pass.$O\
	span.$O\
	enam.$O\
	$TARGMODEL.$O\

HFILES=\
	l.h\
	../kc/k.out.h\
	${ROOT}/include/ar.h\

LIBS=bio 9		# order is important

BIN=$ROOT/$OBJDIR/bin

<$ROOT/mkfiles/mkone-$SHELLTYPE
CFLAGS= $CFLAGS -I.

enam.$O:	../kc/enam.c
	$CC $CFLAGS ../kc/enam.c

$TARGMODEL.$O:	../ld/$TARGMODEL.c
	$CC $CFLAGS ../ld/$TARGMODEL.c
