<../../../mkconfig

TARG=iar	# inferno archiver

OFILES=	ar.$O\
	$TARGMODEL.$O\

HFILES=	${ROOT}/include/a.out.h\
	${ROOT}/include/bio.h\
	${ROOT}/include/mach.h\

LIBS=mach bio 9		# libbio.a uses lib9.a so order matters.

BIN=$ROOT/$OBJDIR/bin

<$ROOT/mkfiles/mkone-$SHELLTYPE

