#                                              -*-makefile-*-
<../../../mkconfig

TARG=ql

OFILES=\
	asm.$O\
	list.$O\
	obj.$O\
	optab.$O\
	pass.$O\
	span.$O\
	enam.$O\
	noop.$O\
	asmout.$O\
	cnam.$O\
	sched.$O\
	$TARGMODEL.$O\

HFILES=\
	l.h\
	../qc/q.out.h\
	${ROOT}/include/ar.h\

LIBS=bio 9			# order is important

BIN=$ROOT/$OBJDIR/bin

<$ROOT/mkfiles/mkone-$SHELLTYPE


enam.$O:	../qc/enam.c
	$CC $CFLAGS ../qc/enam.c
