<../../../mkconfig

TARG=7a
OFILES=\
	y.tab.$O\
	lex.$O\

HFILES=\
	../7c/7.out.h\
	y.tab.h\
	a.h\

YFILES=a.y\

LIBS=cc bio 9		# order is important

BIN=$ROOT/$OBJDIR/bin
<$ROOT/mkfiles/mkone-$SHELLTYPE
YFLAGS=-D1 -d

lex.$O:	../cc/macbody ../cc/lexbody
