<../../../mkconfig

TARG=sed

OFILES=	sed.$O\

HFILES= $ROOT/include/bio.h\
	$ROOT/include/regexp.h\

LIBS=regexp bio 9		# libbio.a uses lib9.a so order matters.

CFLAGS=$CFLAGS -I$ROOT/include

BIN=$ROOT/$OBJDIR/bin

<$ROOT/mkfiles/mkone-$SHELLTYPE
