#                                              -*-makefile-*-
<../../../mkconfig

TARG=2l
OFILES=\
	asm.$O\
	obj.$O\
	optab.$O\
	pass.$O\
	span.$O\
	list.$O\
	enam.$O\
	$TARGMODEL.$O\

HFILES=\
	l.h\
	../2c/2.out.h\
	${ROOT}/include/ar.h\

LIBS=bio 9
BIN=$ROOT/$OBJDIR/bin
<$ROOT/mkfiles/mkone-$SHELLTYPE

CFLAGS=	$CFLAGS -I ${ROOT}/include

enam.$O:	../2c/enam.c
	$CC $CFLAGS ../2c/enam.c
