<../../../mkconfig

TARG=ilex
OFILES=lmain.$O\
	y.tab.$O\
	sub1.$O\
	sub2.$O\
	header.$O\

HFILES=ldefs.h\

LIBS=bio 9

BIN=$ROOT/$OBJDIR/bin

YFILES=parser.y\

<$ROOT/mkfiles/mkone-$SHELLTYPE

install:V:  $ROOT/lib/lex.ncform

$ROOT/lib/lex.ncform:  ncform
	rm -f $target && cp $prereq $target

