name: C

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: |
        ./configure
        . ./env
        mkdir Linux/amd64/lib
        mk nuke
        mk install
