<../../../mkconfig

TARG=6l

OFILES=\
	asm.$O\
	list.$O\
	obj.$O\
	optab.$O\
	pass.$O\
	span.$O\
	enam.$O\
	$TARGMODEL.$O\

HFILES=\
	l.h\
	../6c/6.out.h\
	${ROOT}/include/ar.h\

LIBS=bio 9			# order is important


BIN=$ROOT/$OBJDIR/bin

<$ROOT/mkfiles/mkone-$SHELLTYPE

enam.$O:	../6c/enam.c
	$CC $CFLAGS ../6c/enam.c

